
# configuracion de la base de datos
version: "3.8"
services:
  postgres:
    image: postgres:16.2
    container_name: sistema_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_sistema
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"